name: encrypt
version: 4.1.1
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  asn1lib: ^1.0.0
  clock: ^1.1.0
  collection: ^1.15.0
  crypto: ^3.0.1
  pointycastle:
    git:
      url: https://github.com/Danielherresan/pc-dart
      ref: feature/null-safety

dev_dependencies:
  test: ^1.17.2
